#!/bin/bash
#Copyright (C) 2021 TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

note_metadata="---\ntitle: %s\nsubtitle: %s\ndate: %s\ntags: [%s]\n\n---"
note=""
action=""

create_note()
{
    echo "creating note..."
    path=$(dirname $note)
    note_name=$(basename $note)
    [ -f "$note" ] && echo "note already exists!" && exit 1
    [ -d "$path" ] || mkdir "$path"
    echo "# $note_name" > "$note"

    echo "$note_name created!"
}

usage()
{
    echo "usage:"
    exit 0
}

parse_arguments()
{
    # https://stackoverflow.com/a/31443098
    # https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash#13359121
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -n | --new | new )
                if [ ! -z "$2" ]; then
                    [ -z "$note" ] && note="$2";
                    shift; # Shift value
                fi
                shift ;; # Shift argument
            -t=* | --title=* | title=* )
                if [ ! -z "${1#*=}" ]; then
                    title="${1#*=}"
                fi
                shift ;;
            -s=* | --subtitle=* | subtitle=* )
                if [ ! -z "${1#*=}" ]; then
                    subtitle="${1#*=}"
                fi
                shift ;;
            --tags=* | tags=* )
                if [ ! -z "${1#*=}" ]; then
                    tags="${1#*=}"
                fi
                shift ;;
            -l | --list | list)
                if [ -z "$2" ]; then
                    echo "Listing..."
                    exit -1
                fi
                find "$2" -name "*.md" -o -name "*.txt"
                shift;;
            -o | --open | open)
                if [ ! -z "$2" ]; then
                    xdg-open "$2"
                    exit 0
                fi
                shift;;
            -h | --help | help) usage; shift ;;
            -*)
                echo "unknown option: $1" >&2; exit 1;;
            *) PARAMS="$PARAMS $1"; shift ;;
        esac
    done
}

arguments="$@"
[ -z "$arguments" ] && usage || parse_arguments "$@"
echo "Nome do arquivo: $note"
echo "Título: $title"
echo "Subtítulo: $subtitle"
echo "Data: $(date +"%F %H:%M:%S")"
echo "Tags: $tags"

if [ -z "$note" ]; then
    echo "deve informar um path"
elif [ -f "$note" ]; then
    echo "nota já existe"
else
    echo "cria nota"
fi
